site_name: Application-Hub context
site_description: 'Application-Hub context'
# Repository

repo_name: 'eoepca/application-hub-context'
repo_url: 'https://github.com/EOEPCA/zapplication-hub-context'
edit_uri: 'blob/main/docs/src/'
site_url: 'https://eoepca.github.io/application-hub-context/'


theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list

plugins:
  - search
  - mkdocs-jupyter

nav:
  - Introduction: 'index.md'
  - Kubernetes: 'k8s.md'
  - Configuration: 'configuration.md'
  - JupyterHub API: 'jupyterhub-api.md'
  - Config: 'apphub-config-general.md'
